config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :landing, only: [:index, :show]

  resources :loan_types
  resources :documents
  resources :loans
  resources :loan_documents, only: [:edit, :update]

  root 'loans#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
# frozen_string_literal: true
class Document < ApplicationRecord
  belongs_to :parent, class_name: 'Document', optional: true,
                      inverse_of: :children
  has_many :children, class_name: 'Document', dependent: :destroy,
                      inverse_of: :parent, foreign_key: :parent_id

  has_one_attached :file

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :file, attached: true
end

# == Schema Information
#
# Table name: documents
#
#  id         :bigint           not null, primary key
#  title      :string
#  parent_id  :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/loan.rb
# frozen_string_literal: true
class Loan < ApplicationRecord
  belongs_to :loan_type
  has_many :loan_documents, dependent: :destroy, inverse_of: :loan

  enum state: { pending: 0, started: 1, completed: 2 }

  validates :state, :amount, :loan_type, presence: true
  validates :amount, numericality: true

  after_initialize :init_as_pending
  before_create :preset_documents

  def all_documents_approved?
    loan_documents.all?(&:approved)
  end

  private

  def init_as_pending
    self.state = :pending
  end

  def preset_documents
    loan_type.documents.each do |document|
      loan_documents.build(document: document)
    end
  end
end

# == Schema Information
#
# Table name: loans
#
#  id           :bigint           not null, primary key
#  amount       :float            not null
#  state        :integer          not null
#  loan_type_id :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

app/models/loan_document.rb
# frozen_string_literal: true
class LoanDocument < ApplicationRecord
  belongs_to :loan
  belongs_to :document

  has_one_attached :file

  validates :approved, inclusion: [true, false]
end

# == Schema Information
#
# Table name: loan_documents
#
#  id          :bigint           not null, primary key
#  loan_id     :bigint
#  document_id :bigint
#  approved    :boolean          default(FALSE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/models/loan_type.rb
# frozen_string_literal: true
class LoanType < ApplicationRecord
  has_and_belongs_to_many :documents, join_table: :loan_type_documents,
                                      dependent: :destroy

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :document_ids, presence: true
end

# == Schema Information
#
# Table name: loan_types
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
# frozen_string_literal: true

# Controller actions for documents
class DocumentsController < ApplicationController
  before_action :set_document, except: %i[index new create]

  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(document_params)

    if @document.save
      flash[:success] = 'Document created successfully'
      redirect_to documents_path
    else
      flash.now[:error] = 'Error creating the document'
      render :new
    end
  end

  def edit; end

  def update
    if @document.update(document_params)
      flash[:success] = 'Document updated successfully'
      redirect_to documents_path
    else
      flash.now[:error] = 'Error updating the document'
      render :edit
    end
  end

  def destroy
    @document.destroy
    flash[:info] = 'The document has been deleted'
    redirect_to documents_path
  end

  private

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :file)
  end
end

app/controllers/landing_controller.rb
# frozen_string_literal: true

# Controller actions for landing page
class LandingController < ApplicationController
  layout 'landing'

  def index; end

  def show;end
end

app/controllers/loan_documents_controller.rb
class LoanDocumentsController < ApplicationController
  before_action :find_loan_document, only: [:edit, :update]

  def edit;end

  def update
    if @loan_document.update(document_params)
      flash[:success] = 'Document updated successfully'
      redirect_to loan_path(@loan_document.loan.id)
    else
      flash.now[:error] = 'Error updating the document'
      render :edit
    end
  end

  private

  def document_params
    params.require(:loan_document).permit(:file, :status)
  end

  def find_loan_document
    @loan_document = LoanDocument.find(params[:id])
  end
end

app/controllers/loan_types_controller.rb
# frozen_string_literal: true

# Controller actions for loan_types
class LoanTypesController < ApplicationController
  before_action :set_loan_type, except: %i[index new create]
  before_action :set_documents, only: %i[new create edit update]

  def index
    @loan_types = LoanType.includes(:documents)
  end

  def new
    @loan_type = LoanType.new
  end

  def create
    @loan_type = LoanType.new(loan_type_params)
    if @loan_type.save
      flash[:success] = 'Loan type created successfully'
      redirect_to loan_types_path
    else
      flash.now[:error] = 'Error creating the loan type'
      render :new
    end
  end

  def edit; end

  def update
    if @loan_type.update(loan_type_params)
      flash[:success] = 'Loan type updated successfully'
      redirect_to loan_types_path
    else
      flash.now[:error] = 'Error updating the loan type'
      render :edit
    end
  end

  def destroy
    @loan_type.destroy
    flash[:info] = 'The loan type has been deleted'
    redirect_to loan_types_path
  end

  private

  def set_loan_type
    @loan_type = LoanType.includes(:documents).find(params[:id])
  end

  def set_documents
    @documents = Document.all
  end

  def loan_type_params
    params.require(:loan_type).permit(:name, document_ids: [])
  end
end

app/controllers/loans_controller.rb
# frozen_string_literal: true

# Controller actions for home pages
class LoansController < ApplicationController
  before_action :set_loan, except: %i[index new create]

  def index
    @loans = Loan.includes(:loan_type, :loan_documents)
  end

  def show; end

  def new
    @loan = Loan.new
  end

  def create
    @loan = Loan.new(loan_params)

    if @loan.save
      flash[:success] = 'Loan created successfully'
      redirect_to @loan
    else
      flash.now[:error] = 'Error creating the loan'
      render :new
    end
  end

  def edit; end

  def update
    if @loan.update(loan_params)
      flash[:success] = 'Loan updated successfully'
      redirect_to @loan
    else
      flash.now[:error] = 'Error updating the loan'
      render :edit
    end
  end

  def destroy
    @loan.destroy
    flash[:info] = 'The loan has been deleted'
    redirect_to loans_path
  end

  private

  def set_loan
    @loan = Loan.includes(:loan_type, :loan_documents).find(params[:id])
  end

  def loan_params
    params.require(:loan).permit(:amount, :loan_type_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loan_helper.rb
# frozen_string_literal: true

# View helpers for loans
module LoanHelper
  def loan_types
    @loan_types ||= LoanType.all
  end
end

app/views/documents/_form.slim
= form_for @document do |f|
  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Title
      = f.text_field :title, class: 'form-control'

      - if @document.errors[:title].any?
        .form-text.text-danger
          = @document.errors[:title].join(', ')

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label File
      = f.file_field :file, class: 'form-control'

      - if @document.errors[:file].any?
        .form-text.text-danger
          = @document.errors[:file].join(', ')

  .row.justify-content-center.mt-4
    .col-6.text-center
      = f.submit :Save, class: 'btn btn-primary'
      = link_to 'Cancel', documents_path, class: 'btn btn-link ms-2'

app/views/documents/edit.slim
.container-fluid
  .row
    .col-12
      h1.text-center Editing #{@document.title}

  = render partial: 'form'

app/views/documents/index.slim
.container-fluid
  .row
    .col-12
      h1.text-center Documents

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      .row.justify-content-end.mb-3
        .col-3.text-end
          = link_to 'New', new_document_path, class: 'btn btn-primary'

      - if @documents.any?
        table.table.table-bordered.table-striped.table-hover
          thead
            tr
              th scope="col" Title
              th scope="col"
          tbody
              - @documents.each do |document|
                tr
                  td = document.title
                  td
                    = link_to 'Download', url_for(document.file),
                                          class: 'btn btn-link btn-sm'
                    = link_to 'Edit', edit_document_path(document),
                                      class: 'btn btn-link btn-sm'
                    = link_to 'Remove', document,
                              method: :delete, 'data-confirm': 'Are you sure?',
                              class: 'btn btn-link btn-sm text-danger'

      - else
        .alert.alert-info.text-center role="alert" No records yet

app/views/documents/new.slim
.container-fluid
  .row
    .col-12
      h1.text-center Create new document

  = render partial: 'form'

app/views/home/index.slim
.container-fluid
  .row
    .col-12
      h1 Loan Documents Management System

app/views/landing/index.slim
.container-fluid
  .row.justify-content-center.my-5.d-none.d-md-flex
    .col-9
      .row.raffles
        .col.title.text-vertical.no-img Rifas
        .col.img = image_tag 'landing/bavaria.png', class: 'img-fluid'
        .col.img = image_tag 'landing/bamboo.png', class: 'img-fluid'
        .col.img = image_tag 'landing/adan_eva.png', class: 'img-fluid'

  .row.justify-content-center.my-3.d-md-none
    .col-11.col-sm-9
      .row.raffles
        .col-6.img.logo
          = image_tag 'landing/quedate-casa.png', class: 'img-fluid'
        .col-6.title.no-img Rifas
        .col-6.img = image_tag 'landing/bavaria.png', class: 'img-fluid'
        .col-6.img = image_tag 'landing/bamboo.png', class: 'img-fluid'
        .col-6.img = image_tag 'landing/adan_eva.png', class: 'img-fluid'
        .col-6.img = image_tag 'landing/adan_eva.png', class: 'img-fluid'

.container-fluid.blue-stripe.d-none.d-md-flex

.container-fluid
  .row.justify-content-center.my-4
    .col-11.col-sm-9
      .row.promos
        .col-6.title Promos
        .col-6.sitting-guy.d-none.d-md-flex
          = image_tag 'landing/sitting_guy.png'
        .col-12 = image_tag 'landing/promo_adan_eva.png', class: 'img-fluid'
        .col-12.mt-3 = image_tag 'landing/promo_bamboo.png', class: 'img-fluid'

.container-fluid.bg-white.py-4
  .row.justify-content-center
    .col-11.col-sm-9
      .row.delivery
        .col-5.col-sm-6.text
          span.blue ¿QUERÉS CONOCER
          span.skyblue NUESTRAS OPCIONES DE DELIVERY?
          a.btn.btn-lg.yellow.blue.px-5.d-none.d-md-flex href="#" Click aquí
          a.btn.btn-sm.yellow.blue.px-4.mt-2.d-md-none href="#" Click aquí
        .col-7.col-sm-6.bicycle
          = image_tag 'landing/bicycle.png', class: 'img-fluid'

app/views/landing/show.slim
section#first-section
  .container-fluid.top
    .content-header-fr
      = image_tag 'new_landing/02_Wave.png', :class => 'wave'
      .row
        .col
          .live-content-logo
              figure.contenido.mb-0
                = image_tag 'new_landing/CONTENIDO.png', :class => 'img-fluid'
              .content-bottom
                figure.triangles.p-0
                  = image_tag 'new_landing/00_Triangulos.png', :class => 'img-fluid'
                figure.in.p-0
                  = image_tag 'new_landing/EN.png', :class => 'img-fluid'
                figure.live.p-0
                  = image_tag 'new_landing/VIVO.png'
        .col.content-guitar
          .col.img = image_tag 'new_landing/01_Guitarra.png'
          p.nex-days Estos son los eventos en vivo en los próximos días
  .container-fluid.bottom
    .content-footer-fr
      .content-slick
        .row.align-items-center.justify-content-around
          - 5.times do
            .slick.col.p-2
              .slick-header
              .slick-body
                p.artist.m-0 Artista / Evento
                p.time.m-0 00 MARZO • 00:00
                p.small.mb-0 Lorem ipsum dolor sit amet
              .slick-footer
                span.text 11
                span.icon
                  = image_tag 'new_landing/sms.png'
                span.text 48
                span.icon
                  = image_tag 'new_landing/heart.png'
          end

section#second-section

app/views/layouts/_flash.slim
- flash.each do |key, value|
  ruby:
    puts "key", key, "value", value
    klass = if key == 'notice'
      'success'
    elsif key == 'alert'
      'warning'
    elsif key == 'error'
      'danger'
    elsif %w[success warning info danger]
      key
    else
      'info'
    end

  .alert.alert-dismissible.fade.show class="alert-#{klass}" role="alert"
    = value
    button.btn-close data-bs-dismiss="alert" aria-label="Close"

app/views/layouts/_landing_navbar.slim
nav.navbar.navbar-expand-md.navbar-dark
  .container-fluid
    button.navbar-toggler[aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation"
      data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse"
      type="button"]
      span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-md-0.ms-5.ms-sm-0
        li.nav-item
          a.nav-link href="#" Home
        li.nav-item
          a.nav-link href="#" Promociones
        li.nav-item
          a.nav-link href="#" HomeHappy news
        li.nav-item
          a.nav-link href="#" Shows
        li.nav-item
          a.nav-link href="#" Delivery

      div.navbar-nav.buttons.ms-auto.mb-2.mb-md-0.me-3
        div.nav-item
          a.btn.skyblue href="#" Ingresá
        div.nav-item
          a.btn.yellow href="#" Registrate

app/views/layouts/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    a.navbar-brand href="#" LDM

    button.navbar-toggler[aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation"
      data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse"
      type="button"]
      span.navbar-toggler-icon

    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        li.nav-item
          a.nav-link href=loans_path Loans
        li.nav-item
          a.nav-link href=loan_types_path Loan types
        li.nav-item
          a.nav-link href=documents_path Documents
        li.nav-item
          a.nav-link href=landing_index_path Landing

app/views/layouts/application.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title Loans
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag :application, media: :all,
                                        'data-turbolinks-track': :reload
    = javascript_pack_tag :application, 'data-turbolinks-track': :reload

  body
    = render partial: 'layouts/navbar'
    = render partial: 'layouts/flash'

    = yield

app/views/layouts/landing.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title Landing
    meta content="width=device-width,initial-scale=1" name="viewport"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag :landing, media: :all,
                                    'data-turbolinks-track': :reload
    = stylesheet_link_tag :new_landing, media: :all,
                                    'data-turbolinks-track': :reload
    = javascript_pack_tag :landing, 'data-turbolinks-track': :reload

  body
    = render partial: 'layouts/landing_navbar'
    = yield

app/views/loan_documents/_form.slim
= form_for @loan_document do |f|
  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Upload File
      = f.file_field :file, class: 'form-control'

      - if @loan_document.errors[:file].any?
        .form-text.text-danger
          = @loan_document.errors[:file].join(', ')

  .row.justify-content-center.mt-4
    .col-6.text-center
      = f.submit :Save, class: 'btn btn-primary'
      = link_to 'Cancel', loan_path(@loan_document.loan.id), class: 'btn btn-link ms-2'

app/views/loan_documents/edit.slim
.container-fluid
  .row.mt-3
    .col-12
      h1.text-center Upload Document To Loan ##{ @loan_document.loan.id }

  .row.justify-content-center.mt-3
    .col-12.col-sm-8.col-md-6
      h4.text-center Document: #{@loan_document.document.title}

  .row.justify-content-center.mt-3
    .col-12.col-sm-8.col-md-6
      table.table.table-bordered.table-striped.table-hover
        tbody
          tr
            th style="width: 40%" Document
            td = @loan_document.document.file.filename
          tr
            th Approved
            td = @loan_document.approved ? 'Yes' : 'No'
          tr
            th User Document
            td.text-capitalize = @loan_document.file.filename

  = render partial: 'form'

app/views/loan_types/_form.slim
= form_for @loan_type do |f|
  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Name
      = f.text_field :name, class: 'form-control'

      - if @loan_type.errors[:name].any?
        .form-text.text-danger
          = @loan_type.errors[:name].join(', ')

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Documents
      = f.collection_check_boxes :document_ids, @documents, :id, :title do |d|
        .form-check
          = d.check_box class: 'form-check-input'
          = d.label class: 'form-check-label'

      - if @loan_type.errors[:document_ids].any?
        .form-text.text-danger
          = @loan_type.errors[:document_ids].join(', ')

  .row.justify-content-center.mt-4
    .col-6.text-center
      = f.submit :Save, class: 'btn btn-primary'
      = link_to 'Cancel', loan_types_path, class: 'btn btn-link ms-2'

app/views/loan_types/edit.slim
.container-fluid
  .row
    .col-12
      h1.text-center Editing #{@loan_type.name}

  = render partial: 'form'

app/views/loan_types/index.slim
.container-fluid
  .row
    .col-12
      h1.text-center Loan types

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      .row.justify-content-end.mb-3
        .col-3.text-end
          = link_to 'New', new_loan_type_path, class: 'btn btn-primary'

      - if @loan_types.any?
        table.table.table-bordered.table-striped.table-hover
          thead
            tr
              th scope="col" Name
              th scope="col" # documents
              th scope="col"
          tbody
              - @loan_types.each do |ltype|
                tr
                  td = ltype.name
                  td = ltype.documents.count
                  td
                    = link_to 'Edit', edit_loan_type_path(ltype),
                                      class: 'btn btn-link btn-sm'
                    = link_to 'Remove', ltype,
                              method: :delete, confirm: 'Are you sure?',
                              class: 'btn btn-link btn-sm text-danger'

      - else
        .alert.alert-info.text-center role="alert" No records yet

app/views/loan_types/new.slim
.container-fluid
  .row
    .col-12
      h1.text-center Create new loan type

  = render partial: 'form'

app/views/loans/_form.slim
= form_for @loan do |f|
  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Amount
      = f.number_field :amount, class: 'form-control'

      - if @loan.errors[:amount].any?
        .form-text.text-danger
          = @loan.errors[:amount].join(', ')

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6
      label.form-label Type
      = f.collection_select :loan_type_id, loan_types, :id, :name,
                            { prompt: '-Select-' }, class: 'form-control'

      - if @loan.errors[:loan_type].any?
        .form-text.text-danger
          = @loan.errors[:loan_type].join(', ')

  .row.justify-content-center.mt-4
    .col-6.text-center
      = f.submit :Save, class: 'btn btn-primary'
      = link_to 'Cancel', loans_path, class: 'btn btn-link ms-2'

app/views/loans/edit.slim
.container-fluid
  .row
    .col-12
      h1.text-center Editing ##{@loan.id}

  = render partial: 'form'

app/views/loans/index.slim
.container-fluid
  .row
    .col-12
      h1.text-center Loans

  .row.justify-content-center.mt-3
    .col-12.col-sm-8.col-md-6
      .row.justify-content-end.mb-3
        .col-3.text-end
          = link_to 'New', new_loan_path, class: 'btn btn-primary'

      - if @loans.any?
        table.table.table-bordered.table-striped.table-hover
          thead
            tr
              th scope="col" Amount
              th scope="col" Type
              th scope="col" # documents
              th scope="col"
          tbody
              - @loans.each do |loan|
                tr
                  td = number_to_currency(loan.amount)
                  td = loan.loan_type.name
                  td = loan.loan_documents.count
                  td
                    = link_to 'Details', loan, class: 'btn btn-link btn-sm'
                    = link_to 'Edit', edit_loan_path(loan),
                                      class: 'btn btn-link btn-sm'
                    = link_to 'Remove', loan,
                              method: :delete, 'data-confirm': 'Are you sure?',
                              class: 'btn btn-link btn-sm text-danger'

      - else
        .alert.alert-info.text-center role="alert" No records yet

app/views/loans/new.slim
.container-fluid
  .row
    .col-12
      h1.text-center Create new loan

  = render partial: 'form'

app/views/loans/show.slim
.container-fluid
  .row.mt-3
    .col-12
      h1.text-center Details of loan ##{@loan.id}

  .row.justify-content-center.mt-3
    .col-12.col-sm-8.col-md-6
      table.table.table-bordered.table-striped.table-hover
        tbody
          tr
            th style="width: 40%" Amount
            td = number_to_currency(@loan.amount)
          tr
            th Type
            td = @loan.loan_type.name
          tr
            th State
            td.text-capitalize = @loan.state

  .row.justify-content-center.mt-2
    .col-12.col-sm-8.col-md-6.text-end
      = link_to 'Edit', edit_loan_path(@loan), class: 'btn btn-outline-primary'
      = link_to 'Remove', @loan, method: :delete,
                                 'data-confirm': 'Are you sure?',
                                 class: 'btn btn-outline-danger ms-2'

  .row.mt-4
    .col-12
      h3.text-center Documents

  .row.justify-content-center.mt-3
    .col-12.col-sm-8.col-md-6
      table.table.table-bordered.table-striped.table-hover
        thead
          tr
            th Name
            th Approved
            th Loaded
            th

        tbody
          - @loan.loan_documents.each do |ldoc|
            tr id="loan_document_#{ldoc.id}"
              td.font-monospace = ldoc.document.file.filename
              td.text-capitalize = ldoc.approved ? 'Yes' : 'No'
              td =ldoc.file.present? ? 'Yes' : 'No'
              td.text-truncate
                = link_to 'Download', url_for(ldoc.document.file),
                          class: 'btn btn-link btn-sm', target: '_blank',
                          id: "upload_document_#{ldoc.id}" 

                = link_to "Upload", edit_loan_document_path(ldoc.id)